/* =====================================================
   WORDN'T PLAYER PERSONALITY — trained K-Means model
   Auto-generated by train_model.py — do not hand-edit.

   Feature order: ['attempted', 'survived', 'avgWordLength', 'avgResponseTime', 'mistakes', 'longestStreak']
===================================================== */

const WORDNT_AI_MODEL = {

  featureNames: ["attempted", "survived", "avgWordLength", "avgResponseTime", "mistakes", "longestStreak"],

  // mean/std used to standardize a raw feature vector the same way
  // the training data was standardized before K-Means was trained
  featureMeans: [11.71, 7.48, 5.634587325493579, 3.1107222433317734, 3.42, 5.62],
  featureStds: [3.4446915681959105, 4.007443075079172, 1.678660315237373, 1.521686950306642, 3.599111001344638, 3.668187563361498],

  // the 5 cluster centers K-Means found, in STANDARDIZED space
  centroids: [[-0.2786896826593917, 0.47287009808930647, 1.2561860455898513, 0.28567835381370515, -0.6654421047600985, 0.6488217842980165], [1.1800766250108605, 1.5333967033027909, -0.7211097164935685, -1.0796644027125204, -0.7349037023342215, 1.2008655293414963], [0.4325496116275972, -0.363074402490734, 0.9322795804607688, -0.009515007347289871, 0.6126512906037649, -0.5574960289451443], [-1.33829108027062, -0.419219928649095, -0.4126619073477452, 1.5297108092384843, -0.7904729803935201, -0.005452283901664052], [0.004354526291552751, -1.2239724702522685, -1.0546940022093056, -0.726209752992377, 1.5781674968840738, -1.2867390007927053]],

  // cluster index -> personality key (decided by analyzing each
  // centroid's feature values, see train_model.py)
  centroidLabels: ["word_nerd", "speed_demon", "risk_taker", "careful_player", "chaos_player"]

};
